version: '3.8'

services:
  api:
    build:
      context: ./src/API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${SUPABASE_CONNECTION_STRING}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=EventTicketing
      - Jwt__Audience=EventTicketingUsers
      - Jwt__ExpiryMinutes=60
    networks:
      - app-network

  frontend:
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${API_URL}
        - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
        - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
        - REACT_APP_USE_SUPABASE=${USE_SUPABASE}
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge