name: Deploy Application to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    # Verificación de secretos necesarios
    - name: Check required secrets
      run: |
        if [[ -z "${{ secrets.JWT_SECRET_KEY }}" ]]; then
          echo "Error: JWT_SECRET_KEY is not set"
          exit 1
        fi
        if [[ -z "${{ secrets.SUPABASE_CONNECTION_STRING }}" ]]; then
          echo "Error: SUPABASE_CONNECTION_STRING is not set"
          exit 1
        fi
        if [[ -z "${{ secrets.API_URL }}" ]]; then
          echo "Error: API_URL is not set"
          exit 1
        fi
        echo "All required secrets are set"
      shell: bash

    # Configuración de .NET con caché
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore src/API/API.csproj

    - name: Build
      run: dotnet build src/API/API.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test tests/UnitTests/EventTicketing.UnitTests/EventTicketing.UnitTests.csproj --verbosity normal

    - name: Publish .NET App
      run: dotnet publish src/API/API.csproj -c Release -o publish

    # Build Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/Frontend/package.json

    - name: Get API URL from Terraform
      run: |
        cd terraform
        API_URL=$(terraform output -raw api_url 2>/dev/null || echo "")
        if [[ -z "$API_URL" ]]; then
          echo "Warning: API_URL not available from Terraform, using default"
          API_URL="https://your-api-app.azurewebsites.net/api"
        fi
        echo "API_URL=${API_URL}" >> $GITHUB_ENV
      shell: bash

    - name: Install Frontend Dependencies
      run: |
        cd src/Frontend
        npm install

    - name: Build Frontend
      run: |
        cd src/Frontend
        npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.API_URL }}
        REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    # Actualiza los archivos de configuración reemplazando los placeholders con secretos
    - name: Update appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: 'publish/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        Jwt.Key: ${{ secrets.JWT_SECRET_KEY }}

    # Despliegue de la API en Azure Web App
    - name: Deploy API to Azure Web App
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish

    # Despliegue del Frontend en Azure Storage
    - name: Login to Azure
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Frontend to Azure Storage
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Verificar que los secretos estén configurados
          if [ -z "${{ secrets.STORAGE_ACCOUNT_NAME }}" ]; then
            echo "Error: STORAGE_ACCOUNT_NAME secret is not configured"
            exit 1
          fi
          
          if [ -z "${{ secrets.STORAGE_ACCOUNT_KEY }}" ]; then
            echo "Error: STORAGE_ACCOUNT_KEY secret is not configured"
            exit 1
          fi
          
          # Verificar que el directorio build existe
          if [ ! -d "./src/Frontend/build" ]; then
            echo "Error: Frontend build directory not found"
            exit 1
          fi
          
          # Subir archivos al blob storage
          az storage blob upload-batch \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --auth-mode key \
            --account-key "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
            --destination '$web' \
            --source ./src/Frontend/build \
            --overwrite