name: Deploy Application to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Configuración de .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore src/API/API.csproj

    - name: Build
      run: dotnet build src/API/API.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test tests/UnitTests/EventTicketing.UnitTests/EventTicketing.UnitTests.csproj --verbosity normal

    - name: Publish .NET App
      run: dotnet publish src/API/API.csproj -c Release -o publish

    # Actualizar configuración con secretos
    - name: Update appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: 'publish/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        Jwt.Key: ${{ secrets.JWT_SECRET_KEY }}

    # Despliegue usando el secret API_URL
    - name: Deploy API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish